title: Hello my name is Timur
author: Timur Toktassynov
email: timur.toktassynov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Timur Toktassynov Software Engineer, postgraduate student at University College London studying MSc Software Systems Engineering

# social links
twitter_username: ttoktassynov # DO NOT include the @ character, or else the build will fail!
github_username:  ttoktassynov # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
